#include <gtest/gtest.h>

#include <imgui.h>
#include <imnodes.h>

#include "NodeGraph/Components/NodeGraphNodeFactory.hpp"
#include "NodeGraph/Components/NodeGraphNodes/Keywords/Function.hpp"
#include "NodeGraph/FlowScript/FlowScript.hpp"

namespace
{
    constexpr const char* kGeneratedBanner = "-- Generated by FlowScript::compile()\n";

    class FlowScriptTestHarness final : public FlowScript
    {
    public:
        NodeGraphNode* addFunctionNode(const std::vector<std::string>& args)
        {
            return factory.addFunctionNode(nodes, args);
        }

    private:
        NodeGraphComponents::NodeGraphIdAllocator allocator;
        NodeGraphComponents::NodeGraphNodeFactory factory{&allocator};
    };

    class FlowScriptCompile : public ::testing::Test
    {
    protected:
        void SetUp() override
        {
            ImGui::CreateContext();
            ImNodes::CreateContext();

            ImGuiIO& io = ImGui::GetIO();
            io.DisplaySize = ImVec2(1280.0f, 720.0f);
            io.DeltaTime = 1.0f / 60.0f;
            unsigned char* fontPixels = nullptr;
            int fontWidth = 0;
            int fontHeight = 0;
            io.Fonts->GetTexDataAsRGBA32(&fontPixels, &fontWidth, &fontHeight);
        }

        void TearDown() override
        {
            ImNodes::DestroyContext();
            ImGui::DestroyContext();
        }
    };
}

TEST_F(FlowScriptCompile, shouldCompileFlowGraphAndPrefixGeneratedBanner)
{
    FlowScriptTestHarness flowScript;
    auto* fnNode = dynamic_cast<NodeGraphComponents::Node::Keywords::Function*>(flowScript.addFunctionNode({}));
    ASSERT_NE(fnNode, nullptr);
    fnNode->functionName = "condition";

    const std::string compiledLua = flowScript.compile();

    EXPECT_EQ(compiledLua, std::string(kGeneratedBanner) + "function condition()\nend");
    EXPECT_TRUE(flowScript.getCompileDiagnostics().empty());
}

TEST_F(FlowScriptCompile, shouldCaptureCompileErrorAndClearDiagnosticsAfterSuccessfulRecompile)
{
    FlowScriptTestHarness flowScript;
    auto* fnNode = dynamic_cast<NodeGraphComponents::Node::Keywords::Function*>(flowScript.addFunctionNode({}));
    ASSERT_NE(fnNode, nullptr);

    fnNode->functionName.clear();
    const std::string invalidCompileLua = flowScript.compile();

    EXPECT_EQ(invalidCompileLua, std::string(kGeneratedBanner));
    ASSERT_FALSE(flowScript.getCompileDiagnostics().empty());
    EXPECT_NE(flowScript.getCompileDiagnostics().front().find("Function node requires a function name"), std::string::npos);

    fnNode->functionName = "fixed";
    const std::string validCompileLua = flowScript.compile();

    EXPECT_EQ(validCompileLua, std::string(kGeneratedBanner) + "function fixed()\nend");
    EXPECT_TRUE(flowScript.getCompileDiagnostics().empty());
}

