//
// Created by subha on 25-03-2026.
//

#include "../Headers/NodeGraph/FlowScript/FlowScript.hpp"
#include <EngineState.hpp>
#include <imgui.h>
#include <sstream>
#include <stdexcept>

#include "NodeGraph/Views/NodeGraphNodesView.hpp"
#include "NodeGraph/FlowScript/Compile/Compiler.hpp"
#include "NodeGraph/FlowScript/Decompile/DecompileGraphBuilder.hpp"
#include "NodeGraph/FlowScript/Decompile/LuaSubsetLineParser.hpp"
#include "NodeGraph/FlowScript/LuaEmitter.hpp"


FlowScript::FlowScript()
{
    setScreenSpaceUi(
        [](NodeGraphRenderContext& ctx, void* user) {
            auto* self = static_cast<FlowScript*>(user);

            ImGui::SetCursorPos(ImVec2(8.0f, 8.0f));
            ImGui::BeginGroup();

            if (ImGui::SmallButton("Compile"))
                self->compile();
            if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayShort))
                ImGui::SetTooltip("Compiles the graph to Lua and stores the result");

            const bool hasCompiled = !self->compiledLua.empty();
            if (!hasCompiled)
                ImGui::BeginDisabled();

            if (ImGui::SmallButton("Copy Lua"))
            {
                if (!self->compiledLua.empty())
                    ImGui::SetClipboardText(self->compiledLua.c_str());
            }
            if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayShort))
                ImGui::SetTooltip("Copies the compiled Lua to the clipboard");

            if (ImGui::SmallButton("Execute"))
            {
                if (!self->compiledLua.empty())
                {
                    getLuaEngine().setPrintHandler([self](const std::string& line) {
                        self->appendLuaLog(line);
                    });
                    try
                    {
                        getLuaEngine().runChunk(self->compiledLua, "FlowScript");
                    }
                    catch (const std::exception& ex)
                    {
                        self->appendLuaLog(std::string("[LUA] ") + ex.what());
                    }
                }
            }
            if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayShort))
                ImGui::SetTooltip("Executes the compiled Lua in the Lua runtime");

            if (!hasCompiled)
                ImGui::EndDisabled();

            ImGui::SameLine();
            if (ImGui::SmallButton("Clear Log"))
            {
                self->luaConsoleLines.clear();
            }
            if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayShort))
                ImGui::SetTooltip("Clears the Lua console output");

            ImGui::EndGroup();

            ImGui::SetCursorPos(ImVec2(8.0f, 72.0f));
            ImGui::BeginChild("LuaConsole", ImVec2(360.0f, 140.0f), true);
            for (const auto& line : self->luaConsoleLines)
                ImGui::TextUnformatted(line.c_str());
            if (self->luaConsoleScrollToBottom)
            {
                ImGui::SetScrollHereY(1.0f);
                self->luaConsoleScrollToBottom = false;
            }
            ImGui::EndChild();
        },
        this);
}

void FlowScript::clearScript()
{
    clearNodes();
    clearNodeGraphLinks();
    clearComments();
}

const std::string& FlowScript::compile()
{
    Flowscript::Compile::Compiler compiler;
    const Flowscript::Compile::CompileResult result = compiler.Compile(nodes, nodeGraphLinks);

    compileDiagnostics = result.diagnostics;

    LuaEmitter emitter;
    std::string emittedLua = emitter.Emit(result.statements);

    if (!emittedLua.empty())
        compiledLua = "-- Generated by FlowScript::compile()\n" + emittedLua;
    else
        compiledLua = "-- Generated by FlowScript::compile()\n";

    for (const auto& message : compileDiagnostics)
        appendLuaLog(std::string("[COMPILE] ") + message);

    return compiledLua;
}

void FlowScript::appendLuaLog(const std::string& line)
{
    if (luaConsoleLines.size() >= kLuaConsoleMaxLines)
        luaConsoleLines.erase(luaConsoleLines.begin());
    luaConsoleLines.push_back(line);
    luaConsoleScrollToBottom = true;
}

void FlowScript::deCompile(const std::string& luaCode)
{
    auto* nodeView = views.findView<NodeGraphNodesView>();
    if (!nodeView)
        throw std::runtime_error("NodeGraphNodesView not available");

    Flowscript::Decompile::LuaSubsetLineParser parser;
    Flowscript::Decompile::DecompileGraphBuilder builder(nodes, nodeGraphLinks, *nodeView);

    std::istringstream stream(luaCode);
    std::string rawLine;
    while (std::getline(stream, rawLine))
    {
        const auto statement = parser.parse(rawLine);
        if (!statement)
            continue;
        builder.apply(*statement);
    }

    builder.finalize();
}
