//
// Created by subha on 26-03-2026.
//

#include "../Headers/NodeGraph/FlowScript/StatemachineFlowScript.hpp"

#include <NodeGraph/Views/NodeGraphNodesView.hpp>

#include <exception>
#include <regex>
#include <sstream>
#include <vector>

namespace
{
    const std::string kDefaultConditionChunk =
        "return function(t)\n"
        "    return false\n"
        "end";
}

StatemachineFlowScript::StatemachineFlowScript():
selectedLink(nullptr), showUI(false)
{

}

const std::string& StatemachineFlowScript::defaultConditionChunk()
{
    return kDefaultConditionChunk;
}

std::string StatemachineFlowScript::trimCopy(const std::string& value)
{
    const auto begin = value.find_first_not_of(" \t\r\n");
    if (begin == std::string::npos)
        return "";
    const auto end = value.find_last_not_of(" \t\r\n");
    return value.substr(begin, end - begin + 1);
}

std::string StatemachineFlowScript::unwrapConditionChunk(const std::string& storedCondition)
{
    const std::string trimmed = trimCopy(storedCondition);
    if (trimmed.empty())
        return "local node_0 = function(t)\n    return false\nend\n";

    if (trimmed.rfind("return function(", 0) != 0)
        return storedCondition;

    std::istringstream stream(storedCondition);
    std::string line;
    std::vector<std::string> lines;
    while (std::getline(stream, line))
        lines.push_back(line);

    if (lines.size() < 3)
        return "local node_0 = function(t)\n    return false\nend\n";

    // Remove outer wrapper line (return function(...)) and final end.
    std::vector<std::string> body(lines.begin() + 1, lines.end() - 1);

    // Drop wrapper tail return if present (e.g. return node_6(t)).
    for (int i = static_cast<int>(body.size()) - 1; i >= 0; --i)
    {
        const std::string stripped = trimCopy(body[i]);
        if (stripped.empty())
            continue;
        if (stripped.rfind("return ", 0) == 0)
            body.erase(body.begin() + i);
        break;
    }

    std::ostringstream out;
    for (const auto& bodyLine : body)
    {
        out << bodyLine << "\n";
    }

    const std::string unwrappedBody = trimCopy(out.str());
    if (unwrappedBody.empty())
        return "local node_0 = function(t)\n    return false\nend\n";

    return out.str();
}

void StatemachineFlowScript::ensureContextNode()
{
    if (contextMembers.empty())
        return;

    for (const auto& node : nodes)
    {
        if (node && node->name() == "GenericType(t)")
            return;
    }

    auto* nodeView = views.findView<NodeGraphNodesView>();
    if (!nodeView)
        return;

    nodeView->addGenericTypeNode(nodes, "t", contextMembers, ImVec2(120.0f, 120.0f));
}

std::string StatemachineFlowScript::wrapCompiledEditorScript(const std::string& compiledEditorScript)
{
    std::istringstream stream(compiledEditorScript);
    std::string line;
    std::vector<std::string> bodyLines;
    std::string entryFunctionName;
    const std::regex functionDeclRegex(R"(^\s*local\s+(node_\d+)\s*=\s*function\s*\()", std::regex::ECMAScript);

    while (std::getline(stream, line))
    {
        const std::string stripped = trimCopy(line);
        if (stripped.empty())
            continue;
        if (stripped.rfind("-- Generated by FlowScript::compile()", 0) == 0)
            continue;

        std::smatch match;
        if (std::regex_search(line, match, functionDeclRegex) && match.size() > 1)
            entryFunctionName = match[1].str();

        bodyLines.push_back(line);
    }

    std::ostringstream wrapped;
    wrapped << "return function(t)\n";
    for (const auto& bodyLine : bodyLines)
        wrapped << bodyLine << "\n";

    if (!entryFunctionName.empty())
        wrapped << "    return " << entryFunctionName << "(t)\n";
    else
        wrapped << "    return false\n";

    wrapped << "end";
    return wrapped.str();
}

void StatemachineFlowScript::setSelectedLink(StateMachineLink* link)
{
    clearScript();
    selectedLink = link;
    showUI = true;

    if (!selectedLink)
        return;

    if (selectedLink->condition.empty())
        selectedLink->condition = defaultConditionChunk();

    std::string editorSource = unwrapConditionChunk(selectedLink->condition);
    setCompiledLua(editorSource);
    try
    {
        deCompile(editorSource);
    }
    catch (const std::exception&)
    {
        // Legacy/invalid snippets should still open with a usable starter graph.
        clearScript();
        editorSource = "local node_0 = function(t)\n    return false\nend\n";
        setCompiledLua(editorSource);
        deCompile(editorSource);
    }
    ensureContextNode();
}

void StatemachineFlowScript::draw()
{
    if (!showUI || !selectedLink) return;

    ImGui::Begin("Statemachine flow script", &showUI);

    ImGui::TextUnformatted("Flow script");

    drawUIEmbedded();

    ImGui::End();
}

const std::string& StatemachineFlowScript::compile()
{
    FlowScript::compile();
    auto& luaCode = getCompiledLua();
    if (selectedLink)
    {
        selectedLink->condition = wrapCompiledEditorScript(luaCode);
    }
    return luaCode;
}

